blank_issues_enabled: false
contact_links:
  - name: Nuxt Community Discord
    url: https://discord.nuxtjs.org/
    about: Consider asking questions about the module here.
  - name: nuxt-i18n documentation
    url: https://nuxt-community.github.io/nuxt-i18n/
    about: Check our documentation before reporting issues or questions.
